### ISSUE TITLE
"attribute ghc865 missing"

### ISSUE THREAD

**Issue by mwotton** [vaibhavsagar/notebooks#2]
entirely possible that this is me doing something stupid, but building chart-diagrams gives me this:

```
~/projects/notebooks/chart-diagrams master               ⌚ 10:33:24
➜ nix-build --show-trace
error: while evaluating the attribute 'passAsFile' of the derivation 'ihaskell-with-packages' at /nix/store/v39bvqmsb5qqd7xacc5van16i7lbf89i-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'passAsFile' at /nix/store/v39bvqmsb5qqd7xacc5van16i7lbf89i-source/pkgs/build-support/buildenv/default.nix:77:5:
while evaluating the attribute 'haskell.packages.ghc865.override' at /nix/store/v39bvqmsb5qqd7xacc5van16i7lbf89i-source/pkgs/top-level/haskell-packages.nix:121:3:
attribute 'ghc865' missing, at /nix/store/29has0fy1i5g38k8f6w8lrnvgi2svh7r-source/release.nix:32:21

~/projects/notebooks/chart-diagrams master               ⌚ 10:33:26
➜ nix --version
nix (Nix) 2.3.15
```

any thoughts on what I might have gotten wrong? I'm a bit of a newbie to Nix.

**Comment by vaibhavsagar** [comment]
The notebook `default.nix` is out of date. Let me see if it's an easy fix.

**Comment by vaibhavsagar** [comment]
I needed to change `ghc865` in `default.nix` to `ghc8104`. Updated and pushed, can you try again with the latest changes and see if it works for you now?

**Comment by mwotton** [comment]
i don't see an update, but i changed it locally and it seems to be doing something. thanks! i'll report back when it finishes.

**Comment by vaibhavsagar** [comment]
Huh, I pushed but it didn't succeed :sweat_smile:. [Here](https://github.com/vaibhavsagar/advent-of-code/blob/bb833eb69dbfdb75dfea583198a616f1f7769ba3/2018/notebooks/Day10.ipynb) is an example of using `ihaskell-charts` that might come in handy.

**Comment by vaibhavsagar** [comment]
Any luck?

**Comment by mwotton** [comment]
was swimming with my kids :) but it looks like it worked! i'll play around, thanks.
