### ISSUE TITLE
works beautifully on intel Mac

### ISSUE THREAD

**Issue by nrolland** [vaibhavsagar/notebooks#3]
Hi, I just want to say, it works beautifully on Intel Mac : `$(nix-build)/bin/jupyter-notebook` and you are done !

This is quite amazing to me.

Thanks for sharing those.

(and unfortunately not so much on M1, with the same error as https://github.com/NixOS/nixpkgs/issues/127902 )

**Comment by vaibhavsagar** [comment]
Thanks for letting me know!
